name: Ci/CD 

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-varsion: 5.0.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t maxkortnev/asp:latest .
          docker push maxkortnev/asp:latest
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull maxkortnev/asp:latest
            docker stop asp || true
            docker rm asp || true
            docker run -d --name asp -p 80:80 maxkortnev/asp:latest
